# Generated by Django 4.2.3 on 2023-10-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(default=True)),
                ('age', models.PositiveIntegerField(blank=True)),
                ('gender', models.CharField(max_length=250)),
                ('ph', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('dept', models.TextField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('purpose', models.CharField(max_length=250)),
                ('material', models.CharField(max_length=250)),
            ],
        ),
    ]
