# Generated by Django 4.2.3 on 2023-10-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
