# Generated by Django 4.2.3 on 2023-10-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='store',
            name='dept',
            field=models.CharField(max_length=250),
        ),
    ]
